"""initial schema

Revision ID: 06f05fb8e99b
Revises: 
Create Date: 2026-09-08 15:07:54.675862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = '06f05fb8e99b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_email'), 'farmers', ['email'], unique=True)
    op.create_table('farms',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_farmer_id'), 'farms', ['farmer_id'], unique=False)
    op.create_table('rovers',
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('device_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sprayer_status', sa.String(length=30), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rovers_device_id'), 'rovers', ['device_id'], unique=True)
    op.create_index(op.f('ix_rovers_farmer_id'), 'rovers', ['farmer_id'], unique=False)
    op.create_table('edge_events',
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=False),
    sa.Column('rover_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('original_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rover_id'], ['rovers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edge_events_device_id'), 'edge_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_edge_events_event_id'), 'edge_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_edge_events_event_type'), 'edge_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_edge_events_received_at'), 'edge_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_edge_events_rover_id'), 'edge_events', ['rover_id'], unique=False)
    op.create_table('fields',
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('crop_type', sa.String(length=80), nullable=True),
    sa.Column('crop_variety', sa.String(length=80), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('zone_resolution_m', sa.Float(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_farm_id'), 'fields', ['farm_id'], unique=False)
    op.create_table('rover_field_assignments',
    sa.Column('rover_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['rover_id'], ['rovers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rover_field_assignments_field_id'), 'rover_field_assignments', ['field_id'], unique=False)
    op.create_index(op.f('ix_rover_field_assignments_rover_id'), 'rover_field_assignments', ['rover_id'], unique=False)
    op.create_table('scan_sessions',
    sa.Column('rover_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('interrupted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['rover_id'], ['rovers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_sessions_field_id'), 'scan_sessions', ['field_id'], unique=False)
    op.create_index(op.f('ix_scan_sessions_rover_id'), 'scan_sessions', ['rover_id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('forecast_rainfall_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_mps', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=80), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_fetched_at'), 'weather_observations', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_weather_observations_field_id'), 'weather_observations', ['field_id'], unique=False)
    op.create_table('zones',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('resolution_m', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_field_id'), 'zones', ['field_id'], unique=False)
    op.create_table('alerts',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dedup_key', sa.String(length=160), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_field_id'), 'alerts', ['field_id'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.create_index(op.f('ix_alerts_zone_id'), 'alerts', ['zone_id'], unique=False)
    op.create_table('camera_observations',
    sa.Column('rover_id', sa.UUID(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.String(length=80), nullable=True),
    sa.Column('frame_id', sa.String(length=120), nullable=True),
    sa.Column('image_uri', sa.String(length=500), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['rover_id'], ['rovers.id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_observations_field_id'), 'camera_observations', ['field_id'], unique=False)
    op.create_index(op.f('ix_camera_observations_rover_id'), 'camera_observations', ['rover_id'], unique=False)
    op.create_index(op.f('ix_camera_observations_scan_session_id'), 'camera_observations', ['scan_session_id'], unique=False)
    op.create_index(op.f('ix_camera_observations_timestamp'), 'camera_observations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_camera_observations_zone_id'), 'camera_observations', ['zone_id'], unique=False)
    op.create_table('environmental_readings',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('rover_id', sa.UUID(), nullable=True),
    sa.Column('sensor_id', sa.String(length=80), nullable=True),
    sa.Column('reading_type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['rover_id'], ['rovers.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_readings_field_id'), 'environmental_readings', ['field_id'], unique=False)
    op.create_index(op.f('ix_environmental_readings_reading_type'), 'environmental_readings', ['reading_type'], unique=False)
    op.create_index(op.f('ix_environmental_readings_rover_id'), 'environmental_readings', ['rover_id'], unique=False)
    op.create_index(op.f('ix_environmental_readings_timestamp'), 'environmental_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_environmental_readings_zone_id'), 'environmental_readings', ['zone_id'], unique=False)
    op.create_table('irrigation_events',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('water_volume_l', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irrigation_events_field_id'), 'irrigation_events', ['field_id'], unique=False)
    op.create_index(op.f('ix_irrigation_events_started_at'), 'irrigation_events', ['started_at'], unique=False)
    op.create_index(op.f('ix_irrigation_events_zone_id'), 'irrigation_events', ['zone_id'], unique=False)
    op.create_table('rover_positions',
    sa.Column('rover_id', sa.UUID(), nullable=False),
    sa.Column('scan_session_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('heading_deg', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['rover_id'], ['rovers.id'], ),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rover_positions_field_id'), 'rover_positions', ['field_id'], unique=False)
    op.create_index(op.f('ix_rover_positions_rover_id'), 'rover_positions', ['rover_id'], unique=False)
    op.create_index(op.f('ix_rover_positions_scan_session_id'), 'rover_positions', ['scan_session_id'], unique=False)
    op.create_index(op.f('ix_rover_positions_timestamp'), 'rover_positions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_rover_positions_zone_id'), 'rover_positions', ['zone_id'], unique=False)
    op.create_table('spray_recommendations',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('target_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('target_latitude', sa.Float(), nullable=True),
    sa.Column('target_longitude', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spray_recommendations_field_id'), 'spray_recommendations', ['field_id'], unique=False)
    op.create_index(op.f('ix_spray_recommendations_zone_id'), 'spray_recommendations', ['zone_id'], unique=False)
    op.create_table('advisories',
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('what', sa.String(length=255), nullable=False),
    sa.Column('where_label', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_alert_id'), 'advisories', ['alert_id'], unique=False)
    op.create_index(op.f('ix_advisories_field_id'), 'advisories', ['field_id'], unique=False)
    op.create_index(op.f('ix_advisories_zone_id'), 'advisories', ['zone_id'], unique=False)
    op.create_table('cnn_detections',
    sa.Column('observation_id', sa.UUID(), nullable=False),
    sa.Column('detection_type', sa.String(length=30), nullable=False),
    sa.Column('class_name', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('model_version', sa.String(length=40), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['camera_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cnn_detections_class_name'), 'cnn_detections', ['class_name'], unique=False)
    op.create_index(op.f('ix_cnn_detections_created_at'), 'cnn_detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_cnn_detections_detection_type'), 'cnn_detections', ['detection_type'], unique=False)
    op.create_index(op.f('ix_cnn_detections_observation_id'), 'cnn_detections', ['observation_id'], unique=False)
    op.create_table('spray_events',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('rover_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('quantity_ml', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['spray_recommendations.id'], ),
    sa.ForeignKeyConstraint(['rover_id'], ['rovers.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spray_events_completed_at'), 'spray_events', ['completed_at'], unique=False)
    op.create_index(op.f('ix_spray_events_field_id'), 'spray_events', ['field_id'], unique=False)
    op.create_index(op.f('ix_spray_events_rover_id'), 'spray_events', ['rover_id'], unique=False)
    op.create_index(op.f('ix_spray_events_zone_id'), 'spray_events', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spray_events_zone_id'), table_name='spray_events')
    op.drop_index(op.f('ix_spray_events_rover_id'), table_name='spray_events')
    op.drop_index(op.f('ix_spray_events_field_id'), table_name='spray_events')
    op.drop_index(op.f('ix_spray_events_completed_at'), table_name='spray_events')
    op.drop_table('spray_events')
    op.drop_index(op.f('ix_cnn_detections_observation_id'), table_name='cnn_detections')
    op.drop_index(op.f('ix_cnn_detections_detection_type'), table_name='cnn_detections')
    op.drop_index(op.f('ix_cnn_detections_created_at'), table_name='cnn_detections')
    op.drop_index(op.f('ix_cnn_detections_class_name'), table_name='cnn_detections')
    op.drop_table('cnn_detections')
    op.drop_index(op.f('ix_advisories_zone_id'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_field_id'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_alert_id'), table_name='advisories')
    op.drop_table('advisories')
    op.drop_index(op.f('ix_spray_recommendations_zone_id'), table_name='spray_recommendations')
    op.drop_index(op.f('ix_spray_recommendations_field_id'), table_name='spray_recommendations')
    op.drop_table('spray_recommendations')
    op.drop_index(op.f('ix_rover_positions_zone_id'), table_name='rover_positions')
    op.drop_index(op.f('ix_rover_positions_timestamp'), table_name='rover_positions')
    op.drop_index(op.f('ix_rover_positions_scan_session_id'), table_name='rover_positions')
    op.drop_index(op.f('ix_rover_positions_rover_id'), table_name='rover_positions')
    op.drop_index(op.f('ix_rover_positions_field_id'), table_name='rover_positions')
    op.drop_table('rover_positions')
    op.drop_index(op.f('ix_irrigation_events_zone_id'), table_name='irrigation_events')
    op.drop_index(op.f('ix_irrigation_events_started_at'), table_name='irrigation_events')
    op.drop_index(op.f('ix_irrigation_events_field_id'), table_name='irrigation_events')
    op.drop_table('irrigation_events')
    op.drop_index(op.f('ix_environmental_readings_zone_id'), table_name='environmental_readings')
    op.drop_index(op.f('ix_environmental_readings_timestamp'), table_name='environmental_readings')
    op.drop_index(op.f('ix_environmental_readings_rover_id'), table_name='environmental_readings')
    op.drop_index(op.f('ix_environmental_readings_reading_type'), table_name='environmental_readings')
    op.drop_index(op.f('ix_environmental_readings_field_id'), table_name='environmental_readings')
    op.drop_table('environmental_readings')
    op.drop_index(op.f('ix_camera_observations_zone_id'), table_name='camera_observations')
    op.drop_index(op.f('ix_camera_observations_timestamp'), table_name='camera_observations')
    op.drop_index(op.f('ix_camera_observations_scan_session_id'), table_name='camera_observations')
    op.drop_index(op.f('ix_camera_observations_rover_id'), table_name='camera_observations')
    op.drop_index(op.f('ix_camera_observations_field_id'), table_name='camera_observations')
    op.drop_table('camera_observations')
    op.drop_index(op.f('ix_alerts_zone_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_field_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_zones_field_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_weather_observations_field_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_fetched_at'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_scan_sessions_rover_id'), table_name='scan_sessions')
    op.drop_index(op.f('ix_scan_sessions_field_id'), table_name='scan_sessions')
    op.drop_table('scan_sessions')
    op.drop_index(op.f('ix_rover_field_assignments_rover_id'), table_name='rover_field_assignments')
    op.drop_index(op.f('ix_rover_field_assignments_field_id'), table_name='rover_field_assignments')
    op.drop_table('rover_field_assignments')
    op.drop_index(op.f('ix_fields_farm_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_edge_events_rover_id'), table_name='edge_events')
    op.drop_index(op.f('ix_edge_events_received_at'), table_name='edge_events')
    op.drop_index(op.f('ix_edge_events_event_type'), table_name='edge_events')
    op.drop_index(op.f('ix_edge_events_event_id'), table_name='edge_events')
    op.drop_index(op.f('ix_edge_events_device_id'), table_name='edge_events')
    op.drop_table('edge_events')
    op.drop_index(op.f('ix_rovers_farmer_id'), table_name='rovers')
    op.drop_index(op.f('ix_rovers_device_id'), table_name='rovers')
    op.drop_table('rovers')
    op.drop_index(op.f('ix_farms_farmer_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_farmers_email'), table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###
