"""add field growth_stage

Revision ID: ba1391f4095e
Revises: 06f05fb8e99b
Create Date: 2026-09-10 23:14:57.647804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'ba1391f4095e'
down_revision: Union[str, None] = '06f05fb8e99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('growth_stage', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'growth_stage')
    # ### end Alembic commands ###
